CREATE TABLE [breat_cancer_ultrasound]
(
    [id] integer NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [patient_id_f0] nvarchar, 
    [patient_name_f1] nvarchar, 
    [patient_no_of_checks_today_f2] integer, 
    [report_date_f3] date, 
    [report_id_f4] nvarchar, 
    [report_no_of_checks_f5] integer, 
    [operator_id_f6] nvarchar, 
    [interpreter_id_f7] nvarchar, 
    [machine_id_f8] nvarchar, 
    [us_examination_mode_f9_equals_screening_us] bit, 
    [us_examination_mode_f9_equals_diagnostic_us] bit, 
    [us_examination_mode_f9_equals_both] bit, 
    [_00_asymptomatic_screening_f10] bit, 
    [_11_pain_f12] bit, 
    [_12_palpable_mass_f13] bit, 
    [_13_discharge_f14] bit, 
    [_20_screening_mammographic_category_f15_equals_0] bit, 
    [_20_screening_mammographic_category_f15_equals_1] bit, 
    [_20_screening_mammographic_category_f15_equals_2] bit, 
    [_20_screening_mammographic_category_f15_equals_3] bit, 
    [_20_screening_mammographic_category_f15_equals_4] bit, 
    [_20_screening_mammographic_category_f15_equals_5] bit, 
    [fibroadenoma_f31] bit, 
    [fibrocystic_change_f32] bit, 
    [cyst_f33] bit, 
    [other_f34] nvarchar, 
    [_41_s_p_biopsy_wide_excision_bcs_f36] bit, 
    [_42_s_p_breast_augmentation_reconstruction_f37] bit, 
    [_50_other_reasons_for_breast_sono_examination_f38] bit, 
    [us_category_f39_equals_0_category_0] bit, 
    [us_category_f39_equals_1_category_1] bit, 
    [us_category_f39_equals_2_category_2] bit, 
    [us_category_f39_equals_3_category_3] bit, 
    [us_category_f39_equals_4a_category_4a] bit, 
    [us_category_f39_equals_4b_category_4b] bit, 
    [us_category_f39_equals_4c_category_4c] bit, 
    [us_category_f39_equals_5_category_5] bit, 
    [us_category_f39_equals_6_category_6] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_0_category_0] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_1_category_1] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_2_category_2] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_3_category_3] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_4a_category_4a] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_4b_category_4b] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_4c_category_4c] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_5_category_5] bit, 
    [combined_mammogram_and_us_final_category_f40_equals_6_category_6] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_0_no_need_biopsy] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_1_aspiration_cytology] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_2_core_biopsy] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_3_open_biopsy] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_4_mammography] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_5_mri] bit, 
    [biopsy_and_other_evaluation_suggestion_f41_equals_6_other] bit, 
    [pathology_results_f42_equals_0_biopsy] bit, 
    [pathology_results_f42_equals_1_benign] bit, 
    [pathology_results_f42_equals_2_malignant_carcinoma_in_situ] bit, 
    [pathology_results_f42_equals_3_maligant_invasive_cancer] bit, 
    [pathology_results_f42_equals_4_malignant_other] bit, 
    [pathology_results_f42_equals_5_cytology_suspicious] bit, 
    [pathology_results_f42_equals_6_cytology_atypia] bit, 
    [pathology_results_f42_equals_7_cytology_positive] bit, 
    [pathology_results_f42_equals_8_cytology_negative] bit, 
    [pathology_results_f42_equals_9_biopsy_] bit, 
    [overall_summary_f82] nvarchar
);
CREATE TABLE [breat_cancer_ultrasound.benign_lesions_f16]
(
    [id] integer NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [breat_cancer_ultrasound_ref] integer NOT NULL FOREIGN KEY REFERENCES [breat_cancer_ultrasound]([id]), 
    [side_f20_equals_right] bit, 
    [side_f20_equals_left] bit, 
    [quarter_f21_equals_uoq] bit, 
    [quarter_f21_equals_uiq] bit, 
    [quarter_f21_equals_loq] bit, 
    [quarter_f21_equals_liq] bit, 
    [angle_f22] float, 
    [distance_f23] float, 
    [mass_f24] bit, 
    [calcification_f25] bit, 
    [asymmetry_f26] bit, 
    [architecture_distortion_f27] bit, 
    [others_f28] nvarchar, 
    [density_of_breast_f29_equals_a] bit, 
    [density_of_breast_f29_equals_b] bit, 
    [density_of_breast_f29_equals_c] bit, 
    [density_of_breast_f29_equals_d] bit, 
    [recommendation_f30] nvarchar
);
CREATE TABLE [breat_cancer_ultrasound.benign_lesions_f16.test_so_lv2_f17]
(
    [id] integer NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [breat_cancer_ultrasound.benign_lesions_f16_ref] integer NOT NULL FOREIGN KEY REFERENCES [breat_cancer_ultrasound.benign_lesions_f16]([id]), 
    [fill_me_f18] nvarchar, 
    [fill_me2_f19] float
);
CREATE TABLE [breat_cancer_ultrasound.tumour_details_f43]
(
    [id] integer NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [breat_cancer_ultrasound_ref] integer NOT NULL FOREIGN KEY REFERENCES [breat_cancer_ultrasound]([id]), 
    [side_f44_equals_l_] bit, 
    [side_f44_equals_r_] bit, 
    [position_f45] integer, 
    [distance_f46] float, 
    [max_diameter_f47] float, 
    [shape_f48_equals_1_oval] bit, 
    [shape_f48_equals_2_round] bit, 
    [shape_f48_equals_3_irregular] bit, 
    [orientation_f49_equals_1_parallel] bit, 
    [orientation_f49_equals_2_not_parallel] bit, 
    [margin_f50_equals_1_circumscribed] bit, 
    [margin_f50_equals_2_indistinct] bit, 
    [margin_f50_equals_3_angular] bit, 
    [margin_f50_equals_4_microlobulated] bit, 
    [margin_f50_equals_5_spiculated] bit, 
    [echo_pattern_f51_equals_1_anechoic] bit, 
    [echo_pattern_f51_equals_2_hyperechoic] bit, 
    [echo_pattern_f51_equals_3_complex] bit, 
    [echo_pattern_f51_equals_4_hypoechoic] bit, 
    [echo_pattern_f51_equals_5_isoechoic] bit, 
    [posterior_features_f52_equals_1_no_posterior_acoustic_features] bit, 
    [posterior_features_f52_equals_2_enhancement] bit, 
    [posterior_features_f52_equals_3_shadowing] bit, 
    [posterior_features_f52_equals_4_combined_pattern] bit, 
    [_1_architectural_distortion_f54] bit, 
    [_2_duct_changes_f55] bit, 
    [_3_skin_changes_skin_thickening_f56] bit, 
    [_4_skin_changes_skin_retraction_f57] bit, 
    [_5_edema_f58] bit, 
    [vascularity_f59_equals_0_not_assessed] bit, 
    [vascularity_f59_equals_1_vascularity_absent] bit, 
    [vascularity_f59_equals_2_vascularity_internal_vascularity] bit, 
    [vascularity_f59_equals_3_vascularity_vessels_in_rim] bit, 
    [_1_duct_changes_f61] bit, 
    [_2_cooper_s_ligament_changes_f62] bit, 
    [_3_edema_f63] bit, 
    [_4_architectural_distortion_f64] bit, 
    [_5_skin_thickening_f65] bit, 
    [_6_skin_retraction_irregularity_f66] bit, 
    [_1_clustered_microcysts_f68] bit, 
    [_2_complicated_cysts_f69] bit, 
    [_3_mass_in_or_on_skin_f70] bit, 
    [_4_foreign_body_f71] bit, 
    [_5_simple_cyst_f72] bit, 
    [_6_vascularabnormalities_avm_arteriovenousmalformations_pseudoaneurysms_f73] bit, 
    [_7_vascularabnormalities_mondor_disease_f74] bit, 
    [_8_postsurgical_fluid_collection_f75] bit, 
    [_9_fat_necrosis_f76] bit, 
    [_10_lymph_nodes_intramammary_f77] bit, 
    [_11_lymph_nodes_axillary_f78] bit, 
    [calcifications_f79_equals_1_intraductal] bit, 
    [calcifications_f79_equals_2_microcalcifications_out_of_mass] bit, 
    [calcifications_f79_equals_3_microcalcifications_in_mass] bit, 
    [elasticity_assessment_f80_equals_0_not_assessed] bit, 
    [elasticity_assessment_f80_equals_1_soft] bit, 
    [elasticity_assessment_f80_equals_2_intermediate] bit, 
    [elasticity_assessment_f80_equals_3_hard] bit, 
    [tumour_summary_f81] nvarchar
);