//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cenarius.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class breat_cancer_ultrasound_benign_lesions_f16_test_so_lv2_f17
    {
        public int id { get; set; }
        public int breat_cancer_ultrasound_benign_lesions_f16_ref { get; set; }
        public string fill_me_f18 { get; set; }
        public Nullable<double> fill_me2_f19 { get; set; }
    
        public virtual breat_cancer_ultrasound_benign_lesions_f16 breat_cancer_ultrasound_benign_lesions_f16 { get; set; }
    }
}
