//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cenarius.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class breat_cancer_ultrasound_benign_lesions_f16
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public breat_cancer_ultrasound_benign_lesions_f16()
        {
            this.breat_cancer_ultrasound_benign_lesions_f16_test_so_lv2_f17 = new HashSet<breat_cancer_ultrasound_benign_lesions_f16_test_so_lv2_f17>();
        }
    
        public int id { get; set; }
        public int breat_cancer_ultrasound_ref { get; set; }
        public Nullable<bool> side_f20_equals_right { get; set; }
        public Nullable<bool> side_f20_equals_left { get; set; }
        public Nullable<bool> quarter_f21_equals_uoq { get; set; }
        public Nullable<bool> quarter_f21_equals_uiq { get; set; }
        public Nullable<bool> quarter_f21_equals_loq { get; set; }
        public Nullable<bool> quarter_f21_equals_liq { get; set; }
        public Nullable<double> angle_f22 { get; set; }
        public Nullable<double> distance_f23 { get; set; }
        public Nullable<bool> mass_f24 { get; set; }
        public Nullable<bool> calcification_f25 { get; set; }
        public Nullable<bool> asymmetry_f26 { get; set; }
        public Nullable<bool> architecture_distortion_f27 { get; set; }
        public string others_f28 { get; set; }
        public Nullable<bool> density_of_breast_f29_equals_a { get; set; }
        public Nullable<bool> density_of_breast_f29_equals_b { get; set; }
        public Nullable<bool> density_of_breast_f29_equals_c { get; set; }
        public Nullable<bool> density_of_breast_f29_equals_d { get; set; }
        public string recommendation_f30 { get; set; }
    
        public virtual breat_cancer_ultrasound breat_cancer_ultrasound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<breat_cancer_ultrasound_benign_lesions_f16_test_so_lv2_f17> breat_cancer_ultrasound_benign_lesions_f16_test_so_lv2_f17 { get; set; }
    }
}
