//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cenarius.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class breat_cancer_ultrasound_tumour_details_f43
    {
        public int id { get; set; }
        public int breat_cancer_ultrasound_ref { get; set; }
        public Nullable<bool> side_f44_equals_l_ { get; set; }
        public Nullable<bool> side_f44_equals_r_ { get; set; }
        public Nullable<int> position_f45 { get; set; }
        public Nullable<double> distance_f46 { get; set; }
        public Nullable<double> max_diameter_f47 { get; set; }
        public Nullable<bool> shape_f48_equals_1_oval { get; set; }
        public Nullable<bool> shape_f48_equals_2_round { get; set; }
        public Nullable<bool> shape_f48_equals_3_irregular { get; set; }
        public Nullable<bool> orientation_f49_equals_1_parallel { get; set; }
        public Nullable<bool> orientation_f49_equals_2_not_parallel { get; set; }
        public Nullable<bool> margin_f50_equals_1_circumscribed { get; set; }
        public Nullable<bool> margin_f50_equals_2_indistinct { get; set; }
        public Nullable<bool> margin_f50_equals_3_angular { get; set; }
        public Nullable<bool> margin_f50_equals_4_microlobulated { get; set; }
        public Nullable<bool> margin_f50_equals_5_spiculated { get; set; }
        public Nullable<bool> echo_pattern_f51_equals_1_anechoic { get; set; }
        public Nullable<bool> echo_pattern_f51_equals_2_hyperechoic { get; set; }
        public Nullable<bool> echo_pattern_f51_equals_3_complex { get; set; }
        public Nullable<bool> echo_pattern_f51_equals_4_hypoechoic { get; set; }
        public Nullable<bool> echo_pattern_f51_equals_5_isoechoic { get; set; }
        public Nullable<bool> posterior_features_f52_equals_1_no_posterior_acoustic_features { get; set; }
        public Nullable<bool> posterior_features_f52_equals_2_enhancement { get; set; }
        public Nullable<bool> posterior_features_f52_equals_3_shadowing { get; set; }
        public Nullable<bool> posterior_features_f52_equals_4_combined_pattern { get; set; }
        public Nullable<bool> C_1_architectural_distortion_f54 { get; set; }
        public Nullable<bool> C_2_duct_changes_f55 { get; set; }
        public Nullable<bool> C_3_skin_changes_skin_thickening_f56 { get; set; }
        public Nullable<bool> C_4_skin_changes_skin_retraction_f57 { get; set; }
        public Nullable<bool> C_5_edema_f58 { get; set; }
        public Nullable<bool> vascularity_f59_equals_0_not_assessed { get; set; }
        public Nullable<bool> vascularity_f59_equals_1_vascularity_absent { get; set; }
        public Nullable<bool> vascularity_f59_equals_2_vascularity_internal_vascularity { get; set; }
        public Nullable<bool> vascularity_f59_equals_3_vascularity_vessels_in_rim { get; set; }
        public Nullable<bool> C_1_duct_changes_f61 { get; set; }
        public Nullable<bool> C_2_cooper_s_ligament_changes_f62 { get; set; }
        public Nullable<bool> C_3_edema_f63 { get; set; }
        public Nullable<bool> C_4_architectural_distortion_f64 { get; set; }
        public Nullable<bool> C_5_skin_thickening_f65 { get; set; }
        public Nullable<bool> C_6_skin_retraction_irregularity_f66 { get; set; }
        public Nullable<bool> C_1_clustered_microcysts_f68 { get; set; }
        public Nullable<bool> C_2_complicated_cysts_f69 { get; set; }
        public Nullable<bool> C_3_mass_in_or_on_skin_f70 { get; set; }
        public Nullable<bool> C_4_foreign_body_f71 { get; set; }
        public Nullable<bool> C_5_simple_cyst_f72 { get; set; }
        public Nullable<bool> C_6_vascularabnormalities_avm_arteriovenousmalformations_pseudoaneurysms_f73 { get; set; }
        public Nullable<bool> C_7_vascularabnormalities_mondor_disease_f74 { get; set; }
        public Nullable<bool> C_8_postsurgical_fluid_collection_f75 { get; set; }
        public Nullable<bool> C_9_fat_necrosis_f76 { get; set; }
        public Nullable<bool> C_10_lymph_nodes_intramammary_f77 { get; set; }
        public Nullable<bool> C_11_lymph_nodes_axillary_f78 { get; set; }
        public Nullable<bool> calcifications_f79_equals_1_intraductal { get; set; }
        public Nullable<bool> calcifications_f79_equals_2_microcalcifications_out_of_mass { get; set; }
        public Nullable<bool> calcifications_f79_equals_3_microcalcifications_in_mass { get; set; }
        public Nullable<bool> elasticity_assessment_f80_equals_0_not_assessed { get; set; }
        public Nullable<bool> elasticity_assessment_f80_equals_1_soft { get; set; }
        public Nullable<bool> elasticity_assessment_f80_equals_2_intermediate { get; set; }
        public Nullable<bool> elasticity_assessment_f80_equals_3_hard { get; set; }
        public string tumour_summary_f81 { get; set; }
    
        public virtual breat_cancer_ultrasound breat_cancer_ultrasound { get; set; }
    }
}
